### ISSUE TITLE
Foodcritic SublimeText plugin does not exist in package control

### ISSUE THREAD

**Issue by dougli1sqrd** [pelletiermaxime/SublimeLinter-contrib-foodcritic#2]
I followed each of your steps shown in your readme. Everything was fine up until step 2 of "Plugin Installation" where I use "Package Control: Install Package" and type "foodcritic" to find your plugin. When I do this, no plugins show up. Similarly, in the package control website I tried searching for your plugin, but it does not seem to be there.

**Comment by pelletiermaxime** [comment]
As mentionned in issue #1, this isn't in package control, so you have to install it manually.
In linux that means installing it in "~/.config/sublime-text-3/Packages/SublimeLinter-contrib-foodcritic/".
Feel free to send a PR to fix the doc or to fix #1.

**Comment by dougli1sqrd** [comment]
Thanks!
